version: '2.1'

services:
  db:
    image: postgres:17.2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - my-network-name

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/tolma.ch
    networks:
      - my-network-name

networks:
  my-network-name:
    driver: bridge
