definitions:
  user.LoginErrorData:
    properties:
      error:
        example: Invalid credentials
        type: string
    type: object
  user.LoginInputData:
    properties:
      password:
        example: pass
        type: string
      username:
        example: username
        type: string
    type: object
  user.LoginOutputData:
    properties:
      token:
        example: gadsgasfdasfds
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login user based on provided `username` and `password`
      parameters:
      - description: name search by q
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/user.LoginInputData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.LoginOutputData'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/user.LoginErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/user.LoginErrorData'
      summary: Login user
      tags:
      - User
swagger: "2.0"
